name: grow
description: Grow.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  cloud_firestore: ^0.12.6
  firebase_auth: ^0.11.1+10
  google_sign_in: ^4.0.4
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  flutter_screenutil: ^0.4.1
  flutter_swiper: ^1.1.6
  image_picker: ^0.4.5
  permission_handler: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true